name: Skip,Pass,Fail

on: workflow_call

jobs:
    pass:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Passed job would have run here"
    skip:
        runs-on: ubuntu-latest
        if: false
        steps:
            - name: Print Skipped Message
              run: echo "Skipped job would have run here"
    fail:
        runs-on: ubuntu-latest
        steps:
            - name: Fail
              run: exit 255
