name: Skip

on: 
    - workflow_dispatch

jobs:
    skip:
        runs-on: ubuntu-latest
        if: false
        steps:
            - name: Print Skipped Message
              run: echo "Skipped job would have run here"
